# Port of the gateway
server:
  port: 8080

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
        
        - id: feeedback_prosumer_route
          uri: lb://feedback-prosumer-rest
          predicates:
          - Path=/api/reports/feed/**
          filters:
          - RewritePath=/api/reports/feed(?<segment>), /api/feedback-prosumer$\{segment}

        - id: event_merch_prosumer_route
          uri: lb://event-merch-prosumer-rest
          predicates:
          - Path=/api/event-merch/**
          filters:
          - RewritePath=/api/event-merch(?<segment>/?), /api/event-merch-prosumer-rest$\{segment}

        - id: sales_analysis_prosumer_route
          uri: lb://sales-analysis-prosumer-rest
          predicates:
          - Path=/api/reports/sales/**
          filters:
          - RewritePath=/api/reports/sales(?<segment>/?), /api/sales-analysis-prosumer-rest$\{segment}

        - id: merchandise_provider_route
          uri: lb://merchandising-rest
          predicates:
          - Path=/api/merch/**
          filters:
          - RewritePath=/api/merch(?<segment>/?), /api/merchandise-rest$\{segment}

        - id: auth_provider_route
          uri: lb://authentication-rest
          predicates:
          - Path=/api/auth/**
          filters:
          - RewritePath=/api/auth(?<segment>), /api/authentication-rest/auth$\{segment}
        - id: soap_proxy_prosumer_route
          uri: lb://soap-proxy-prosumer-rest
          predicates:
          - Path=/api/proxy/**
          filters:
          - RewritePath=/api/proxy(?<segment>), /api/soap-proxy$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: health,refresh

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
      #defaultZone: http://discovery-server:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
